services:
  dev-db:
    image: postgres:17.0
    container_name: nest-api
    environment:
      POSTGRES_DB: nest_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
